### PR TITLE
Adding v1.10 to the schedule

### PR DESCRIPTION
**Pull request by psschwei**
Signed-off-by: Paul S. Schweigert <paulschw@us.ibm.com>

Keeping in sync with the RELEASE-SCHEDULE in knative/community, updated in https://github.com/knative/community/pull/1140

(leads for serving/eventing picked based on who looked like they were next up in the cycle)

/assign @nader-ziada @matzew

### CODE REVIEW

**Comment by nader-ziada** [comment]
The date for the release is Jan 10th which might be too soon after the December break for the community considering pkg cut is Jan 3rd
@psschwei wdyt?

**Comment by psschwei** [comment]
I was thinking that too...

**Comment by psschwei** [comment]
Let's discuss in [slack](https://knative.slack.com/archives/CU9DGL4FM/p1659457354837629)

**Comment by psschwei** [comment]
As Evan pointed out in Slack, there's a good chance we'll have a new release cadence before the end of the year, so we can probably update the schedule later once that gets worked out.

**Pull request closed without merging**
