### PR TITLE
:gift: Adding kn-plugin-event to the list of releases

### PR DESCRIPTION
**Pull request by cardil**
# Changes

- :gift: Adding kn-plugin-event to the list of releases

/kind enhancement

### CODE REVIEW

**Comment by rhuss** [comment]
Looks good but maybe also add to the list of homebrew formulas like the other plugins ? (just search for `source-kafka` to find all spots)

**Comment by rhuss** [comment]
@cardil any opinion of adding the plugin to the plugin's homebrew formulas ?

**Comment by dprotaso** [comment]
@rhuss @cardil release is next week are you including this plugin?

**Review by maximilien — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
