### PR TITLE
Remove eventing-kafka from release

### PR DESCRIPTION
**Pull request by creydr**
Remove eventing-kafka as repo is archived

### CODE REVIEW

**Review by ReToCode — APPROVED** [review]
/lgtm
/approve

**Comment by dprotaso** [comment]
Hey @creydr  https://github.com/knative-extensions/eventing-kafka doesn't show as archived.

Is there an issue or something somewhere?

**Comment by Cali0707** [comment]
cc @pierDipi ^^

**Comment by dprotaso** [comment]
I removed the prow jobs associated with this repo

**Comment by pierDipi** [comment]
I think we wanted to wait for all community supported versions to become unsupported

**Pull request merged**
