### PR TITLE
add docs to rotation

### PR DESCRIPTION
**Pull request by csantanapr**
adds folks for docs releases 0.23 and 0.24, the goal is to have the process that is fully automated and anyone can cut the release, maybe 1 person to cut just by creating a tag or branch in the docs repo.

### CODE REVIEW

**Comment by csantanapr** [comment]
I think messed up the table with the dates, will fix

**Review by vaikas — APPROVED** [review]
/lgtm
Thanks!

**Review by tcnghia — APPROVED** [review]

**Review by evankanderson — COMMENTED** [review]
/lgtm
/approve

**Comment by csantanapr** [comment]
replaced by #19

**Pull request closed without merging**
