### PR TITLE
Update leads for 1.13

### PR DESCRIPTION
**Pull request by skonto**
# Changes

- Similar to https://github.com/knative/release/pull/249

### CODE REVIEW

**Comment by skonto** [comment]
cc @Cali0707 should I add you?

**Comment by skonto** [comment]
@creydr should I add you?

**Comment by creydr** [comment]
> @creydr should I add you?

Sorry for the late reply, but I was on PTO. I can help for eventing, but I guess we have already enough :shrug:

**Comment by skonto** [comment]
>  but I guess we have already enough 🤷
I will add you and you can help on demand if you have cycles ;)

**Comment by creydr** [comment]
> I will add you and you can help on demand if you have cycles if that is ok ;)

sure. Thanks

**Review by ReToCode — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
